### ISSUE TITLE
Cannot fund an SPV wallet 

### ISSUE THREAD

**Issue by petermchale** [bitcoin-sv/spv-wallet#652]
- [ X ]  Does my issue clearly describe what exactly is not working properly?
- [ X ]  Does my issue clearly describe what are my expectations and what is the current output?
- [ ]  Did I attach logs/screenshots/errors which ocured?
- [ ]  Did I provide information how I run the code/library/application and on which platform/browser?

I set up an account at https://wallet.spv.money/ and received a paymail address. Following https://docs.bsvblockchain.org/network-topology/applications/spv-wallet/quickstart#how-can-i-make-a-transaction-to-the-wallet I tried to send BSV from my Rock Wallet to that paymail address. It failed, presumably because Rock Wallet only supports paymail from certain providers (https://help.rockwallet.com/can-i-use-paymail-to-send-bsv). How do you recommend sending BSV from Rock Wallet to a paymail account created at https://wallet.spv.money/ to try out the functionality of spv-wallet? For example, is it possible to get a bitcoin address from the spv-wallet, e.g., by using the GO client? 

**Expected behavior**
I think it would be good to be able to easily fund an SPV wallet from a standard wallet like Rock Wallet.

**Comment by sirdeggen** [comment]
The problem is actually that Rock Wallet does not even attempt to send to p2p paymail endpoints. They can accept inbound p2p destination and p2p receive rawtx endpoints but do not pay out using those capabilities. They are looking for basic address resolution endpoints - which SPV Wallet does not support.

I am in contact with Rock Wallet development team and have been encouraging this direction for some time now.

**Comment by sirdeggen** [comment]
SPV Wallet is compatible with HandCash, Tokenized, and a number of other wallets in the ecosystem who use p2p-dest and rawtx endpoints.

We will not be supporting address based payments in future, as this is antithetical to the purpose of the wallet.
